index:
  en : index.html
#  fr : index-fr.html

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://2019.pass-the-salt.org # the base hostname & protocol for your site
title:
  - en : "2019 Pass the SALT website"
#  - fr : "Site web Pass the SALT 2018"
permalink: /:slug/

#traductions
translate:
  en:
    home:
      name: "About"
      url: "/"
#  fr:
#    home:
#      name: "Accueil"
#      url: "/accueil/"

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/passthesaltcon
#  - title: github
#    url: http://github.com/pass-the-salt
  - title: envelope
    url: mailto:contact@pass-the-salt.org

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
#paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate

# Build settings
